- name: calling variables from args
  hosts: local
  connection: local
  tasks:
  - name: Variables from args
    ansible.builtin.debug:
      msg: "Course is : {{ COURSE }} and Duration is : {{ DURATION }} and Trainer is : {{ TRAINER }}"




#calling variables through args is by giving Ex: " -e COURSE=AWS WITH DEVOPS -e DURATION=120hrs -e TRAINER=Azeezshk"