- name: Loops
  hosts: local
  connection: local
  tasks:
  - name: print the Loops
    ansible.builtin.debug:
      msg: "Hello from {{ item }}"
    loop:
    - Azeez
    - Azeem
    - Hafsa
    - Chanu